name: 'Build And Deploy Images to Docker Hub'

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_SECRET: "secret1233"
          envkey_TOKEN_SALT_COMPLEXITY: 10
          envkey_MAGIC_LINK_TOKEN_VALIDITY: 3
          envkey_SESSION_SECRET: "secret123456"
          envkey_MAILER_SMTP_URL: "smtps://user@domain.com:pass@smtp.domain.com"
          envkey_MAILER_ADDRESS_FROM: '"From Name Here" <from@example.com>'
          file_name: .env
          fail_on_empty: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
  build-backend:
    runs-on: ubuntu-latest
    needs: prepare
    
    steps:
      - name: List file
        run: ls -la

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./packages/hoppscotch-backend/Dockerfile
          tags: ntq170493/hoppscotch-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    needs: prepare
    
    steps:
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./packages/hoppscotch-selfhost-web/Dockerfile
          tags: ntq170493/hoppscotch-selfhost-web:latest

  build-sh-admin:
    runs-on: ubuntu-latest
    needs: prepare
    
    steps:
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./packages/hoppscotch-sh-admin/Dockerfile
          tags: ntq170493/hoppscotch-sh-admin:latest
